spring:
  application:
    name: movie-catalog-api

  datasource:
    url: jdbc:postgresql://localhost:5432/movies_db
    username: postgres
    password: "0745493242"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:

      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
